version: "3.8"

services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      # Basic broker / node config
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"

      # Listeners & protocols
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      # Internal listeners (for containers / inter-broker)
      KAFKA_LISTENERS: "PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092"
      # How the broker advertises itself (inside Docker + from your laptop)
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # KRaft quorum (no Zookeeper)
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"

      # Single-broker dev setup
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # Logs (inside the container)
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "autonomous-taxi-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"

  taxi-producer:
    build: .
    container_name: taxi-producer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: "kafka:29092"
    command: ["python", "src/producer_taxi.py"]
    restart: on-failure

  fleet-monitor:
    build: .
    container_name: fleet-monitor
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: "kafka:29092"
    command: ["python", "src/consumer_fleet_monitor.py"]
    restart: on-failure
    volumes:
      - ./data:/app/data

  streamlit-dashboard:
    build: .
    container_name: streamlit-dashboard
    depends_on:
      - fleet-monitor
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    command: ["streamlit", "run", "src/dashboard_map.py", "--server.port=8501", "--server.address=0.0.0.0"]
    restart: on-failure
